const KEY='rythumitra_v3';
const oldKeys=['rythumitra_v2','rythumitra_v1'];
let data=JSON.parse(localStorage.getItem(KEY)||'null');
if(!data){
  let old=null;
  for(const k of oldKeys){try{old=JSON.parse(localStorage.getItem(k)||'null');if(old)break}catch(e){}}
  data=old||{farm:{},crops:[],expenses:[],profits:[],reminders:[]};
  data.farm=data.farm||{}; data.crops=data.crops||[]; data.expenses=data.expenses||[]; data.profits=data.profits||[]; data.reminders=data.reminders||[];
  // Migrate the old single-crop farm into the new crop list.
  if(data.crops.length===0 && data.farm.crop){
    data.crops.push({id:Date.now(),name:data.farm.crop,area:Number(data.farm.area||0),sowingDate:data.farm.sowingDate||'',harvestDate:'',stage:'growing',yieldKg:0,priceKg:0});
  }
  // Keep old profit records usable. Older versions stored quintals; convert to kg and ₹/kg.
  data.profits=data.profits.map(p=>{
    if(p.yieldKg!==undefined) return p;
    const q=Number(p.yieldQ||0), pq=Number(p.priceQ||0);
    const kg=q*100, priceKg=pq/100;
    return {...p,yieldKg:kg,priceKg, revenue:kg*priceKg, profit:(kg*priceKg)-Number(p.expenses||0)};
  });
  localStorage.setItem(KEY,JSON.stringify(data));
}
let lang=localStorage.getItem('rythumithra_lang')||'en';
let reminderTimer=null;
const T={
 en:{tagline:'Your Farm. Your Data. Your Better Decision.',greeting:'Good day, Farmer 👋',dashboardIntro:'Manage your farm, crops, daily costs and profit separately.',crop:'🌾 Crops',area:'📐 Total Area',totalExpenses:'💰 Total Expenses',totalProfit:'📈 Total Profit',quickActions:'Quick actions',cropBtn:'Manage Crops',addExpenseBtn:'Add Daily Expense',recordProfitBtn:'Record Profit',cropManagement:'🌱 Crop Management',cropHint:'Add each crop separately. Quantity and selling price use kilograms and ₹/kg.',cropName:'Crop name',cropArea:'Land area (acres)',cropSowingDate:'Sowing date',cropHarvestDate:'Expected harvest date',cropStage:'Crop stage',expectedYield:'Expected yield (kg)',expectedPrice:'Expected price (₹/kg)',expectedIncome:'Expected income',addCrop:'Add Crop',myCrops:'🌾 My Crops',cropHistory:'My Crops',viewAll:'View all',myFarm:'👨‍🌾 Farm Profile',farmerName:'Farmer name',location:'Village / location',saveFarm:'Save Farm Profile',dailyExpenses:'💰 Daily Expenses',expenseHint:'Record each expense separately with its date. Your expense history stays separate from profit history.',category:'Category',amount:'Amount (₹)',date:'Date',note:'Note',addExpense:'Add Expense',expenseHistory:'Expense History',profitCalculator:'📊 Profit Calculator',profitDate:'Profit date',yield:'Expected / actual yield (kg)',price:'Selling price / kg (₹)',profitExpensesInput:'Expenses for this profit record (₹)',profitExpenseHint:'This amount is recorded only for this profit entry. It does not change your daily expense history.',saveProfit:'Calculate & Save Profit',revenue:'Expected Revenue',recordExpenses:'Record Expenses',profit:'Profit',profitHistory:'Profit History',reminders:'🔔 Reminders',reminderHint:'Set a date and time. Allow notifications when your phone asks.',reminderTextLabel:'Reminder',reminderDateLabel:'Date',reminderTimeLabel:'Alarm time',addReminder:'Add Reminder & Alarm',allowNotifications:'Allow Notifications',profile:'👤 Profile',localStorageNote:'Your current data is stored on this device. Cloud sync can be added in a later version.',home:'Home',cropsNav:'Crops',expensesNav:'Expenses',profitNav:'Profit',remindersNav:'Reminders',profileNav:'Profile',growing:'Growing',ready:'Ready',harvested:'Harvested',noCrops:'No crops added yet.',cropAdded:'Crop added successfully.',farmSaved:'Farm profile saved successfully.'},
 te:{tagline:'మీ పొలం. మీ డేటా. మీ మంచి నిర్ణయం.',greeting:'రైతు గారికి శుభదినం 👋',dashboardIntro:'మీ పొలం, పంటలు, రోజువారీ ఖర్చులు మరియు లాభాలను వేరువేరుగా నిర్వహించండి.',crop:'🌾 పంటలు',area:'📐 మొత్తం విస్తీర్ణం',totalExpenses:'💰 మొత్తం ఖర్చులు',totalProfit:'📈 మొత్తం లాభం',quickActions:'త్వరిత చర్యలు',cropBtn:'పంటలు నిర్వహించండి',addExpenseBtn:'రోజువారీ ఖర్చు జోడించండి',recordProfitBtn:'లాభం నమోదు చేయండి',cropManagement:'🌱 పంటల నిర్వహణ',cropHint:'ప్రతి పంటను విడిగా జోడించండి. పరిమాణం కిలోల్లో, ధర ₹/కిలోగా ఉంటుంది.',cropName:'పంట పేరు',cropArea:'భూమి విస్తీర్ణం (ఎకరాలు)',cropSowingDate:'విత్తిన తేదీ',cropHarvestDate:'అంచనా కోత తేదీ',cropStage:'పంట దశ',expectedYield:'అంచనా దిగుబడి (కిలోలు)',expectedPrice:'అంచనా ధర (₹/కిలో)',expectedIncome:'అంచనా ఆదాయం',addCrop:'పంట జోడించండి',myCrops:'🌾 నా పంటలు',cropHistory:'నా పంటలు',viewAll:'అన్నీ చూడండి',myFarm:'👨‍🌾 పొలం వివరాలు',farmerName:'రైతు పేరు',location:'గ్రామం / ప్రాంతం',saveFarm:'పొలం వివరాలు సేవ్ చేయండి',dailyExpenses:'💰 రోజువారీ ఖర్చులు',expenseHint:'ప్రతి ఖర్చును తేదీతో విడిగా నమోదు చేయండి. ఖర్చుల చరిత్ర, లాభాల చరిత్ర వేరుగా ఉంటాయి.',category:'వర్గం',amount:'మొత్తం (₹)',date:'తేదీ',note:'గమనిక',addExpense:'ఖర్చు జోడించండి',expenseHistory:'ఖర్చుల చరిత్ర',profitCalculator:'📊 లాభం లెక్కింపు',profitDate:'లాభం తేదీ',yield:'అంచనా / వాస్తవ దిగుబడి (కిలోలు)',price:'కిలోకు అమ్మక ధర (₹)',profitExpensesInput:'ఈ లాభం లెక్కకు ఖర్చు (₹)',profitExpenseHint:'ఈ మొత్తం ఈ లాభం నమోదుకే వర్తిస్తుంది. ఇది రోజువారీ ఖర్చుల చరిత్రను మార్చదు.',saveProfit:'లాభాన్ని లెక్కించి సేవ్ చేయండి',revenue:'అంచనా ఆదాయం',recordExpenses:'నమోదు చేసిన ఖర్చు',profit:'లాభం',profitHistory:'లాభాల చరిత్ర',reminders:'🔔 రిమైండర్లు',reminderHint:'తేదీ మరియు సమయం పెట్టండి. ఫోన్ అడిగినప్పుడు నోటిఫికేషన్లను అనుమతించండి.',reminderTextLabel:'రిమైండర్',reminderDateLabel:'తేదీ',reminderTimeLabel:'అలారం సమయం',addReminder:'రిమైండర్ & అలారం జోడించండి',allowNotifications:'నోటిఫికేషన్లు అనుమతించండి',profile:'👤 ప్రొఫైల్',localStorageNote:'ప్రస్తుతం మీ డేటా ఈ పరికరంలోనే నిల్వ ఉంటుంది. తరువాత క్లౌడ్ సింక్ జోడించవచ్చు.',home:'హోమ్',cropsNav:'పంటలు',expensesNav:'ఖర్చులు',profitNav:'లాభం',remindersNav:'రిమైండర్లు',profileNav:'ప్రొఫైల్',growing:'పెరుగుతోంది',ready:'కోతకు సిద్ధం',harvested:'కోత పూర్తయింది',noCrops:'ఇంకా పంటలు జోడించలేదు.',cropAdded:'పంట విజయవంతంగా జోడించబడింది.',farmSaved:'పొలం వివరాలు విజయవంతంగా సేవ్ అయ్యాయి.'}
};
const catTe={Seeds:'విత్తనాలు',Fertilizer:'ఎరువులు',Labour:'కూలీలు',Irrigation:'నీటిపారుదల',Machinery:'యంత్రాలు','Crop protection':'పంట రక్షణ',Transport:'రవాణా',Other:'ఇతర'};
function save(){localStorage.setItem(KEY,JSON.stringify(data));updateUI();scheduleReminders()}
function money(n){return '₹'+Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:2})}
function today(){return new Date().toISOString().slice(0,10)}
function showScreen(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));document.getElementById(id).classList.add('active');window.scrollTo({top:0,behavior:'smooth'})}
function toggleLanguage(){lang=lang==='en'?'te':'en';localStorage.setItem('rythumithra_lang',lang);applyLanguage();updateUI()}
function applyLanguage(){document.documentElement.lang=lang==='te'?'te':'en';document.querySelectorAll('[data-i18n]').forEach(el=>{const k=el.dataset.i18n;if(T[lang][k]){if(el.tagName==='LABEL'){const input=el.querySelector('input,select');el.childNodes[0].nodeValue=T[lang][k]+' ';}else el.textContent=T[lang][k]}});document.getElementById('langBtn').textContent=lang==='en'?'తెలుగు':'English';document.querySelectorAll('#expenseCategory option').forEach(o=>o.textContent=lang==='te'?(catTe[o.value]||o.value):o.value)}
function saveFarm(){data.farm={farmerName:document.getElementById('farmerName').value.trim(),location:document.getElementById('location').value.trim()};save();document.getElementById('farmSaved').textContent=T[lang].farmSaved}
function addCrop(){const name=document.getElementById('cropName').value.trim(),area=Number(document.getElementById('cropArea').value||0),sowingDate=document.getElementById('cropSowingDate').value,harvestDate=document.getElementById('cropHarvestDate').value,stage=document.getElementById('cropStage').value,yieldKg=Number(document.getElementById('expectedYield').value||0),priceKg=Number(document.getElementById('expectedPrice').value||0);if(!name||area<=0){alert(lang==='te'?'పంట పేరు మరియు భూమి విస్తీర్ణం నమోదు చేయండి.':'Enter crop name and land area.');return}data.crops.push({id:Date.now(),name,area,sowingDate,harvestDate,stage,yieldKg,priceKg});['cropName','cropArea','cropSowingDate','cropHarvestDate','expectedYield','expectedPrice'].forEach(id=>document.getElementById(id).value='');document.getElementById('cropStage').value='growing';save();alert(T[lang].cropAdded)}
function removeCrop(id){data.crops=data.crops.filter(x=>x.id!==id);save()}
function cropIncome(c){return Number(c.yieldKg||0)*Number(c.priceKg||0)}
function updateExpectedIncome(){const y=Number(document.getElementById('expectedYield').value||0),p=Number(document.getElementById('expectedPrice').value||0);document.getElementById('expectedIncome').textContent=money(y*p)}
function addExpense(){const amount=Number(document.getElementById('expenseAmount').value||0);if(amount<=0){alert(lang==='te'?'దయచేసి సరైన మొత్తాన్ని నమోదు చేయండి.':'Please enter a valid amount.');return}const category=document.getElementById('expenseCategory').value;data.expenses.push({id:Date.now(),category,amount,date:document.getElementById('expenseDate').value||today(),note:document.getElementById('expenseNote').value.trim()});document.getElementById('expenseAmount').value='';document.getElementById('expenseNote').value='';save()}
function removeExpense(id){data.expenses=data.expenses.filter(x=>x.id!==id);save()}
function totalExpenses(){return data.expenses.reduce((s,x)=>s+Number(x.amount||0),0)}
function addProfitPreview(){const revenue=Number(document.getElementById('yieldKg').value||0)*Number(document.getElementById('priceKg').value||0);const expenses=Number(document.getElementById('profitExpenseAmount').value||0);document.getElementById('revenue').textContent=money(revenue);document.getElementById('profitExpenses').textContent=money(expenses);document.getElementById('profitValue').textContent=money(revenue-expenses)}
function recordProfit(){const yieldKg=Number(document.getElementById('yieldKg').value||0),priceKg=Number(document.getElementById('priceKg').value||0),expenses=Number(document.getElementById('profitExpenseAmount').value||0);if(yieldKg<=0||priceKg<0){alert(lang==='te'?'దిగుబడి మరియు అమ్మక ధర నమోదు చేయండి.':'Enter yield and selling price.');return}const revenue=yieldKg*priceKg;data.profits.push({id:Date.now(),date:document.getElementById('profitDate').value||today(),yieldKg,priceKg,expenses,revenue,profit:revenue-expenses});document.getElementById('yieldKg').value='';document.getElementById('priceKg').value='';document.getElementById('profitExpenseAmount').value='';addProfitPreview();save()}
function removeProfit(id){data.profits=data.profits.filter(x=>x.id!==id);save()}
async function requestNotifications(){if(!('Notification' in window)){alert(lang==='te'?'ఈ బ్రౌజర్ నోటిఫికేషన్లను మద్దతు ఇవ్వదు.':'This browser does not support notifications.');return}const p=await Notification.requestPermission();document.getElementById('notificationStatus').textContent=p==='granted'?(lang==='te'?'నోటిఫికేషన్లు అనుమతించబడ్డాయి.':'Notifications enabled.'):(lang==='te'?'నోటిఫికేషన్లు అనుమతించబడలేదు.':'Notifications are not enabled.')}
function addReminder(){const text=document.getElementById('reminderText').value.trim(),date=document.getElementById('reminderDate').value,time=document.getElementById('reminderTime').value;if(!text||!date||!time){alert(lang==='te'?'రిమైండర్, తేదీ మరియు సమయం నమోదు చేయండి.':'Enter reminder, date and time.');return}data.reminders.push({id:Date.now(),text,date,time,done:false});document.getElementById('reminderText').value='';save();requestNotifications()}
function removeReminder(id){data.reminders=data.reminders.filter(x=>x.id!==id);save()}
function scheduleReminders(){clearInterval(reminderTimer);reminderTimer=setInterval(checkReminders,15000);checkReminders()}
function checkReminders(){const now=new Date(),stamp=now.toISOString().slice(0,10),hm=String(now.getHours()).padStart(2,'0')+':'+String(now.getMinutes()).padStart(2,'0');data.reminders.forEach(r=>{if(!r.done&&r.date===stamp&&r.time===hm){r.done=true;localStorage.setItem(KEY,JSON.stringify(data));if('Notification' in window&&Notification.permission==='granted')new Notification('RythuMitra 🔔',{body:r.text});else alert('RythuMitra 🔔\n'+r.text)}});updateUI()}
function stageLabel(stage){return T[lang][stage]||stage}
function cropCard(c){const income=cropIncome(c);return `<div class="crop-card"><div class="crop-main"><div class="crop-title"><strong>🌾 ${escapeHtml(c.name)}</strong><span class="badge">${escapeHtml(stageLabel(c.stage))}</span></div><div class="crop-meta">${lang==='te'?'భూమి':'Area'}: ${c.area} acres · ${lang==='te'?'దిగుబడి':'Yield'}: ${Number(c.yieldKg||0).toLocaleString('en-IN')} kg · ${lang==='te'?'ధర':'Price'}: ${money(c.priceKg)}/kg</div><div class="crop-meta">${lang==='te'?'అంచనా ఆదాయం':'Expected income'}: <strong>${money(income)}</strong>${c.harvestDate?' · '+(lang==='te'?'కోత':'Harvest')+': '+escapeHtml(c.harvestDate):''}</div></div><button onclick="removeCrop(${c.id})">${lang==='te'?'తొలగించు':'Delete'}</button></div>`}
function updateUI(){const totalArea=data.crops.reduce((s,c)=>s+Number(c.area||0),0);document.getElementById('dashCrop').textContent=lang==='te'?`${data.crops.length} పంటలు`:`${data.crops.length} crop${data.crops.length===1?'':'s'}`;document.getElementById('dashArea').textContent=totalArea+' acres';document.getElementById('dashExpenses').textContent=money(totalExpenses());const totalProfit=data.profits.reduce((s,x)=>s+Number(x.profit||0),0);document.getElementById('dashProfit').textContent=money(totalProfit);document.getElementById('farmerName').value=data.farm.farmerName||'';document.getElementById('location').value=data.farm.location||'';document.getElementById('expenseTotal').textContent=money(totalExpenses());
const crops=[...data.crops].sort((a,b)=>b.id-a.id);document.getElementById('cropCount').textContent=data.crops.length;document.getElementById('cropList').innerHTML=crops.length?crops.map(cropCard).join(''):`<p class="muted">${T[lang].noCrops}</p>`;document.getElementById('dashboardCrops').innerHTML=crops.length?crops.slice(0,3).map(cropCard).join(''):`<p class="muted">${T[lang].noCrops}</p>`;
const expenses=[...data.expenses].sort((a,b)=>b.date.localeCompare(a.date)||b.id-a.id);document.getElementById('expenseList').innerHTML=expenses.length?expenses.map(x=>`<div class="expense-row"><div><strong>${escapeHtml(lang==='te'?(catTe[x.category]||x.category):x.category)}</strong><br><small>${escapeHtml(x.date)}${x.note?' · '+escapeHtml(x.note):''}</small></div><div class="row-right"><strong>${money(x.amount)}</strong><button onclick="removeExpense(${x.id})">${lang==='te'?'తొలగించు':'Delete'}</button></div></div>`).join(''):`<p class="muted">${lang==='te'?'ఇంకా ఖర్చులు లేవు.':'No expenses added yet.'}</p>`;
const profitList=document.getElementById('profitList');const profits=[...data.profits].sort((a,b)=>b.date.localeCompare(a.date)||b.id-a.id);profitList.innerHTML=profits.length?profits.map(x=>`<div class="profit-row"><div><strong>${escapeHtml(x.date)}</strong><br><small>${lang==='te'?'దిగుబడి':'Yield'}: ${Number(x.yieldKg||0).toLocaleString('en-IN')} kg · ${lang==='te'?'అమ్మక ధర':'Price'}: ${money(x.priceKg)}/kg<br>${lang==='te'?'ఆదాయం':'Revenue'}: ${money(x.revenue)} · ${lang==='te'?'ఖర్చు':'Expenses'}: ${money(x.expenses)}</small></div><div class="row-right"><strong>${money(x.profit)}</strong><button onclick="removeProfit(${x.id})">${lang==='te'?'తొలగించు':'Delete'}</button></div></div>`).join(''):`<p class="muted">${lang==='te'?'ఇంకా లాభాల నమోదు లేదు.':'No profit records yet.'}</p>`;document.getElementById('profitTotal').textContent=money(totalProfit);
const rem=[...data.reminders].sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));document.getElementById('reminderList').innerHTML=rem.length?rem.map(x=>`<div class="reminder-row"><div><strong>${escapeHtml(x.text)}</strong><br><small>${escapeHtml(x.date)} · ${escapeHtml(x.time)} ${x.done?' · '+(lang==='te'?'పూర్తయింది':'Done'):''}</small></div><button onclick="removeReminder(${x.id})">${lang==='te'?'తొలగించు':'Delete'}</button></div>`).join(''):`<p class="muted">${lang==='te'?'ఇంకా రిమైండర్లు లేవు.':'No reminders yet.'}</p>`;applyLanguage()}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
document.getElementById('expenseDate').value=today();document.getElementById('profitDate').value=today();document.getElementById('reminderDate').value=today();document.getElementById('cropSowingDate').value=today();document.getElementById('yieldKg').addEventListener('input',addProfitPreview);document.getElementById('priceKg').addEventListener('input',addProfitPreview);document.getElementById('profitExpenseAmount').addEventListener('input',addProfitPreview);document.getElementById('expectedYield').addEventListener('input',updateExpectedIncome);document.getElementById('expectedPrice').addEventListener('input',updateExpectedIncome);applyLanguage();updateUI();scheduleReminders();
