@@ -10,7 +10,7 @@ function rmUrl(){const c=rmCloudCfg();return c?.url?.replace(/\/$/,'')||''}
function rmHeaders(token){const c=rmCloudCfg();return {'apikey':c.key,'Authorization':'Bearer '+(token||c.key),'Content-Type':'application/json'}}
function saveCloudConfig(){const url=(document.getElementById('cloudProjectUrl')?.value||'').trim().replace(/\/$/,'');const key=(document.getElementById('cloudAnonKey')?.value||'').trim();if(!/^https:\/\/[^\s]+\.supabase\.co$/.test(url)||key.length<20){rmCloudStatus('Enter a valid Supabase project URL and anon public key.');return}localStorage.setItem(RM_CLOUD_KEY,JSON.stringify({url,key}));rmCloudStatus('Cloud setup saved on this phone. Test the connection next.')}
function loadCloudConfig(){const c=rmCloudCfg();if(!c)return;const u=document.getElementById('cloudProjectUrl'),k=document.getElementById('cloudAnonKey');if(u)u.value=c.url||'';if(k)k.value=c.key||'';const s=rmCloudSession();if(s?.access_token){rmCloudStatus('Cloud session active: '+(s.email||'signed in') ,true)}}
async function testCloudConnection(){const c=rmCloudCfg();if(!c){rmCloudStatus('Save your Supabase setup first.');return}try{const r=await fetch(rmUrl()+'/rest/v1/'+RM_TABLE+'?select=user_user_id&limit=1',{headers:rmHeaders()});if(r.ok||r.status===401){rmCloudStatus(r.ok?'Connection successful. Database table is reachable.':'Project reachable, but the table/auth setup needs checking.');}else{rmCloudStatus(const errorText=await r.text(); rmCloudStatus('Supabase HTTP '+r.status+': '+errorText). Check the SQL setup.')}}catch(e){rmCloudStatus('Could not reach Supabase. Check internet and the project URL.')}}
async function testCloudConnection(){const c=rmCloudCfg();if(!c){rmCloudStatus('Save your Supabase setup first.');return}try{const r=await fetch(rmUrl()+'/rest/v1/'+RM_TABLE+'?select=user_id&limit=1',{headers:rmHeaders()});if(r.ok||r.status===401){rmCloudStatus(r.ok?'Connection successful. Database table is reachable.':'Project reachable, but the table/auth setup needs checking.');}else{rmCloudStatus('Connection reached Supabase, but returned HTTP '+r.status+'. Check the SQL setup.')}}catch(e){rmCloudStatus('Could not reach Supabase. Check internet and the project URL.')}}
async function cloudAuth(path,payload){const c=rmCloudCfg();if(!c)throw new Error('Save cloud setup first.');const r=await fetch(rmUrl()+'/auth/v1/'+path,{method:'POST',headers:rmHeaders(),body:JSON.stringify(payload)});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error_description||j.msg||j.message||('HTTP '+r.status));return j}
async function cloudSignUp(){const email=(document.getElementById('cloudEmail')?.value||'').trim();const password=document.getElementById('cloudPassword')?.value||'';if(!email||password.length<6){rmCloudStatus('Enter an email and a password of at least 6 characters.',true);return}try{const j=await cloudAuth('signup',{email,password});if(j.access_token){localStorage.setItem(RM_SESSION_KEY,JSON.stringify({access_token:j.access_token,refresh_token:j.refresh_token,user:j.user,email:j.user?.email||email}));rmCloudStatus('Cloud account created and signed in.',true)}else rmCloudStatus('Account created. Check your email if confirmation is enabled, then log in.',true)}catch(e){rmCloudStatus(e.message,true)}}
async function cloudSignIn(){const email=(document.getElementById('cloudEmail')?.value||'').trim();const password=document.getElementById('cloudPassword')?.value||'';if(!email||!password){rmCloudStatus('Enter your cloud email and password.',true);return}try{const j=await cloudAuth('token?grant_type=password',{email,password});localStorage.setItem(RM_SESSION_KEY,JSON.stringify({access_token:j.access_token,refresh_token:j.refresh_token,user:j.user,email:j.user?.email||email}));rmCloudStatus('Cloud login successful.',true)}catch(e){rmCloudStatus(e.message,true)}}
