/* RythuMitra V10.9 - Supabase cloud foundation.
   Uses Supabase's public REST/Auth endpoints. No service-role key is ever requested. */
const RM_CLOUD_KEY='rythumitra_cloud_config_v109';
const RM_SESSION_KEY='rythumitra_cloud_session_v109';
const RM_TABLE='farmer_cloud_data';
function rmCloudCfg(){try{return JSON.parse(localStorage.getItem(RM_CLOUD_KEY)||'null')}catch(e){return null}}
function rmCloudSession(){try{return JSON.parse(localStorage.getItem(RM_SESSION_KEY)||'null')}catch(e){return null}}
function rmCloudStatus(msg,auth=false){const el=document.getElementById(auth?'cloudAuthStatus':'cloudBackendStatus');if(el)el.textContent=msg}
function rmUrl(){const c=rmCloudCfg();return c?.url?.replace(/\/$/,'')||''}
function rmHeaders(token){const c=rmCloudCfg();return {'apikey':c.key,'Authorization':'Bearer '+(token||c.key),'Content-Type':'application/json'}}
function saveCloudConfig(){const url=(document.getElementById('cloudProjectUrl')?.value||'').trim().replace(/\/$/,'');const key=(document.getElementById('cloudAnonKey')?.value||'').trim();if(!/^https:\/\/[^\s]+\.supabase\.co$/.test(url)||key.length<20){rmCloudStatus('Enter a valid Supabase project URL and anon public key.');return}localStorage.setItem(RM_CLOUD_KEY,JSON.stringify({url,key}));rmCloudStatus('Cloud setup saved on this phone. Test the connection next.')}
function loadCloudConfig(){const c=rmCloudCfg();if(!c)return;const u=document.getElementById('cloudProjectUrl'),k=document.getElementById('cloudAnonKey');if(u)u.value=c.url||'';if(k)k.value=c.key||'';const s=rmCloudSession();if(s?.access_token){rmCloudStatus('Cloud session active: '+(s.email||'signed in') ,true)}}
async function testCloudConnection(){const c=rmCloudCfg();if(!c){rmCloudStatus('Save your Supabase setup first.');return}try{const r=await fetch(rmUrl()+'/rest/v1/'+RM_TABLE+'?select=id&limit=1',{headers:rmHeaders()});if(r.ok||r.status===401){rmCloudStatus(r.ok?'Connection successful. Database table is reachable.':'Project reachable, but the table/auth setup needs checking.');}else{rmCloudStatus('Connection reached Supabase, but returned HTTP '+r.status+'. Check the SQL setup.')}}catch(e){rmCloudStatus('Could not reach Supabase. Check internet and the project URL.')}}
async function cloudAuth(path,payload){const c=rmCloudCfg();if(!c)throw new Error('Save cloud setup first.');const r=await fetch(rmUrl()+'/auth/v1/'+path,{method:'POST',headers:rmHeaders(),body:JSON.stringify(payload)});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error_description||j.msg||j.message||('HTTP '+r.status));return j}
async function cloudSignUp(){const email=(document.getElementById('cloudEmail')?.value||'').trim();const password=document.getElementById('cloudPassword')?.value||'';if(!email||password.length<6){rmCloudStatus('Enter an email and a password of at least 6 characters.',true);return}try{const j=await cloudAuth('signup',{email,password});if(j.access_token){localStorage.setItem(RM_SESSION_KEY,JSON.stringify({access_token:j.access_token,refresh_token:j.refresh_token,user:j.user,email:j.user?.email||email}));rmCloudStatus('Cloud account created and signed in.',true)}else rmCloudStatus('Account created. Check your email if confirmation is enabled, then log in.',true)}catch(e){rmCloudStatus(e.message,true)}}
async function cloudSignIn(){const email=(document.getElementById('cloudEmail')?.value||'').trim();const password=document.getElementById('cloudPassword')?.value||'';if(!email||!password){rmCloudStatus('Enter your cloud email and password.',true);return}try{const j=await cloudAuth('token?grant_type=password',{email,password});localStorage.setItem(RM_SESSION_KEY,JSON.stringify({access_token:j.access_token,refresh_token:j.refresh_token,user:j.user,email:j.user?.email||email}));rmCloudStatus('Cloud login successful.',true)}catch(e){rmCloudStatus(e.message,true)}}
function cloudSignOut(){localStorage.removeItem(RM_SESSION_KEY);rmCloudStatus('Cloud account signed out.',true)}
function rmCollectData(){const keys=['rythumitra_v6','rythumitra_v7','rythumitra_v8','rythumitra_v9','rythumitra_v10','rythumitra_cloud_config_v109'];const out={version:'10.9',savedAt:new Date().toISOString(),local:{}};for(const k of keys){try{const v=localStorage.getItem(k);if(v!==null)out.local[k]=JSON.parse(v)}catch(e){out.local[k]=localStorage.getItem(k)}}return out}
function rmApplyData(payload){if(!payload?.local)return;for(const [k,v] of Object.entries(payload.local)){if(k===RM_CLOUD_KEY)continue;try{localStorage.setItem(k,JSON.stringify(v))}catch(e){}}if(typeof updateUI==='function')updateUI();if(typeof renderV9All==='function')renderV9All();if(typeof renderV10All==='function')renderV10All()}
async function cloudSyncNow(){const s=rmCloudSession();if(!s?.access_token){rmCloudStatus('Login to your cloud account first.',true);return}try{const payload={user_id:s.user.id,data:rmCollectData(),updated_at:new Date().toISOString()};const r=await fetch(rmUrl()+'/rest/v1/'+RM_TABLE,{method:'POST',headers:{...rmHeaders(s.access_token),'Prefer':'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(payload)});if(!r.ok){const j=await r.json().catch(()=>({}));throw new Error(j.message||j.hint||('HTTP '+r.status))}rmCloudStatus('Your farmer data was uploaded to the cloud.',true)}catch(e){rmCloudStatus('Upload failed: '+e.message,true)}}
async function cloudRestoreNow(){const s=rmCloudSession();if(!s?.access_token){rmCloudStatus('Login to your cloud account first.',true);return}try{const r=await fetch(rmUrl()+'/rest/v1/'+RM_TABLE+'?select=data&user_id=eq.'+encodeURIComponent(s.user.id)+'&limit=1',{headers:rmHeaders(s.access_token)});const j=await r.json().catch(()=>[]);if(!r.ok)throw new Error(j.message||('HTTP '+r.status));if(!j.length){rmCloudStatus('No cloud backup found for this account.',true);return}rmApplyData(j[0].data);rmCloudStatus('Cloud data restored to this phone.',true)}catch(e){rmCloudStatus('Restore failed: '+e.message,true)}}
window.addEventListener('load',loadCloudConfig);
