/* RythuMitra V9 account, buyer, cloud-ready marketplace and admin layer. */
const V9_KEY='rythumitra_v9';
let v9=JSON.parse(localStorage.getItem(V9_KEY)||'null')||{user:null,role:'farmer',buyers:[],enquiries:[],messages:[],notifications:[],ratings:[],reports:[],announcements:[],cloudBackup:null,session:false};
v9.buyers=v9.buyers||[];v9.enquiries=v9.enquiries||[];v9.messages=v9.messages||[];v9.notifications=v9.notifications||[];v9.ratings=v9.ratings||[];v9.reports=v9.reports||[];v9.announcements=v9.announcements||[];
function v9save(){localStorage.setItem(V9_KEY,JSON.stringify(v9));}
function v9esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function v9t(en,te){return lang==='te'?te:en;}
function v9toast(msg){const el=document.getElementById('v9Toast');if(el){el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600);}}
function v9id(){return Date.now()+Math.floor(Math.random()*1000)}
function v9currentFarmer(){return v9.user?.mobile||'guest';}
function v9notify(title,text){v9.notifications.unshift({id:v9id(),title,text,date:new Date().toLocaleString('en-IN'),read:false});v9.notifications=v9.notifications.slice(0,100);v9save();renderV9Notifications();}
function v9openAuth(mode='login'){showScreen('account');document.getElementById('authMode').value=mode;renderV9Account();}
function sendDemoOtp(){const mobile=(document.getElementById('authMobile')?.value||'').replace(/\D/g,'').slice(-10);if(mobile.length!==10){v9toast(v9t('Enter a valid 10-digit mobile number.','చెల్లుబాటు అయ్యే 10 అంకెల మొబైల్ నంబర్ నమోదు చేయండి.'));return}const otp=String(Math.floor(100000+Math.random()*900000));sessionStorage.setItem('rythu_demo_otp',otp);sessionStorage.setItem('rythu_demo_mobile',mobile);document.getElementById('otpHint').textContent=v9t('Demo OTP: '+otp+' (real SMS OTP needs a backend/SMS provider).','డెమో OTP: '+otp+' (నిజమైన SMS OTP కోసం backend/SMS provider అవసరం).');v9toast(v9t('OTP generated for demo.','డెమో కోసం OTP రూపొందించబడింది.'));}
function saveFarmerAccount(){const name=document.getElementById('authName').value.trim(),mobile=document.getElementById('authMobile').value.replace(/\D/g,'').slice(-10),state=document.getElementById('authState').value,district=document.getElementById('authDistrict').value.trim(),mandal=document.getElementById('authMandal').value.trim(),village=document.getElementById('authVillage').value.trim(),otp=document.getElementById('authOtp').value.trim();if(!name||mobile.length!==10){v9toast(v9t('Enter name and valid mobile number.','పేరు మరియు సరైన మొబైల్ నంబర్ నమోదు చేయండి.'));return}const sent=sessionStorage.getItem('rythu_demo_otp'),sentMobile=sessionStorage.getItem('rythu_demo_mobile');if(otp&&(!sent||otp!==sent||sentMobile!==mobile)){v9toast(v9t('OTP does not match. Use Send OTP first.','OTP సరిపోలలేదు. ముందుగా Send OTP నొక్కండి.'));return}v9.user={name,mobile,state,district,mandal,village,photo:v9.user?.photo||'',farming:v9.user?.farming||{crops:[],landArea:'',irrigation:'',farmingType:''},createdAt:v9.user?.createdAt||new Date().toISOString()};v9.role='farmer';v9.session=true;v9save();if(window.data){data.farm=data.farm||{};data.farm.farmerName=name;data.farm.location=[village,mandal,district,state].filter(Boolean).join(', ');localStorage.setItem(typeof KEY!=='undefined'?KEY:'rythumitra_v6',JSON.stringify(data));updateUI?.();}v9notify(v9t('Welcome to RythuMitra','రైతుమిత్రకు స్వాగతం'),v9t('Your farmer account is active.','మీ రైతు ఖాతా యాక్టివ్‌లో ఉంది.'));renderV9Account();renderV9Dashboard();}
function loginFarmer(){const mobile=document.getElementById('authMobile').value.replace(/\D/g,'').slice(-10),otp=document.getElementById('authOtp').value.trim();const sent=sessionStorage.getItem('rythu_demo_otp'),sentMobile=sessionStorage.getItem('rythu_demo_mobile');if(mobile.length!==10||!otp||otp!==sent||mobile!==sentMobile){v9toast(v9t('Use a valid mobile and the demo OTP.','సరైన మొబైల్ మరియు డెమో OTP ఉపయోగించండి.'));return}const old=v9.user&&v9.user.mobile===mobile?v9.user:{name:'Farmer',mobile,state:'',district:'',mandal:'',village:'',photo:'',farming:{}};v9.user=old;v9.role='farmer';v9.session=true;v9save();v9notify(v9t('Login successful','లాగిన్ విజయవంతం'),v9t('Welcome back.','మళ్లీ స్వాగతం.'));renderV9Account();renderV9Dashboard();}
function logoutV9(){v9.session=false;v9.role='farmer';v9save();v9toast(v9t('Logged out.','లాగౌట్ అయ్యింది.'));renderV9Account();}
function recoverAccount(){const mobile=document.getElementById('authMobile').value.replace(/\D/g,'').slice(-10);if(mobile.length!==10){v9toast(v9t('Enter your registered mobile number.','రిజిస్టర్ చేసిన మొబైల్ నంబర్ నమోదు చేయండి.'));return}v9toast(v9t('Recovery request created. Verify identity through your backend/SMS provider in production.','రికవరీ అభ్యర్థన సృష్టించబడింది. నిజమైన యాప్‌లో backend/SMS provider ద్వారా గుర్తింపును ధృవీకరించాలి.'));}
function saveProfile(){if(!v9.user)return;v9.user.name=document.getElementById('profileName').value.trim();v9.user.state=document.getElementById('profileState').value;v9.user.district=document.getElementById('profileDistrict').value.trim();v9.user.mandal=document.getElementById('profileMandal').value.trim();v9.user.village=document.getElementById('profileVillage').value.trim();v9.user.farming={crops:document.getElementById('profileCrops').value,landArea:document.getElementById('profileLand').value,irrigation:document.getElementById('profileIrrigation').value,farmingType:document.getElementById('profileFarming').value};v9save();v9toast(v9t('Profile saved.','ప్రొఫైల్ సేవ్ అయింది.'));renderV9Account();renderV9Dashboard();}
function buyerRegister(){const name=document.getElementById('buyerName').value.trim(),business=document.getElementById('buyerBusiness').value.trim(),mobile=document.getElementById('buyerMobile').value.replace(/\D/g,'').slice(-10),loc=document.getElementById('buyerLocation').value.trim(),type=document.getElementById('buyerType').value;if(!name||mobile.length!==10){v9toast(v9t('Enter buyer name and valid mobile.','కొనుగోలుదారు పేరు మరియు సరైన మొబైల్ నమోదు చేయండి.'));return}v9.buyers.push({id:v9id(),name,business,mobile,location:loc,type});v9.role='buyer';v9.session=true;v9save();v9toast(v9t('Buyer account created.','కొనుగోలుదారు ఖాతా సృష్టించబడింది.'));renderV9Buyer();}
function sendEnquiryV9(listingId){const listing=(data?.listings||[]).find(x=>String(x.id)===String(listingId));if(!listing){v9toast(v9t('Listing not found.','లిస్టింగ్ కనబడలేదు.'));return}if(!v9.session){v9openAuth('login');v9toast(v9t('Login as a buyer/farmer before sending an enquiry.','విచారణ పంపడానికి కొనుగోలుదారు/రైతుగా లాగిన్ అవ్వండి.'));return}const msg=prompt(v9t('Enter your enquiry message:','మీ విచారణ సందేశం నమోదు చేయండి:'))||'';const e={id:v9id(),listingId,farmer:listing.farmer||listing.ownerKey||'Farmer',crop:listing.cropName||listing.crop||'Crop',quantity:listing.kg||0,price:listing.price||0,buyer:v9.user?.name||'Buyer',buyerMobile:v9.user?.mobile||'',message:msg,date:new Date().toISOString(),status:'new'};v9.enquiries.unshift(e);v9notify(v9t('New buyer enquiry','కొత్త కొనుగోలుదారు విచారణ'),`${e.crop} · ${e.buyer}`);v9save();renderV9Buyer();renderV9Comms();v9toast(v9t('Enquiry sent.','విచారణ పంపబడింది.'));}
function updateEnquiryStatus(id,status){const e=v9.enquiries.find(x=>x.id===id);if(!e)return;e.status=status;v9save();v9notify(v9t('Enquiry updated','విచారణ నవీకరించబడింది'),`${e.crop} · ${status}`);renderV9Comms();}
function sendMessageV9(id){const e=v9.enquiries.find(x=>x.id===id);if(!e)return;const msg=prompt(v9t('Message buyer/farmer:','కొనుగోలుదారు/రైతుకు సందేశం:'))||'';if(!msg)return;v9.messages.push({id:v9id(),enquiryId:id,from:v9.user?.name||'User',message:msg,date:new Date().toISOString()});v9notify(v9t('New message','కొత్త సందేశం'),msg);v9save();renderV9Comms();}
function markSoldV9(listingId){const x=(data?.listings||[]).find(x=>String(x.id)===String(listingId));if(!x)return;x.sold=true;localStorage.setItem(KEY,JSON.stringify(data));v9notify(v9t('Crop marked as sold','పంట అమ్మినట్లు గుర్తించబడింది'),x.cropName||'Crop');updateUI?.();renderV9Dashboard();}
function rateV9(kind,id){const score=Number(prompt(v9t('Rating 1-5:','1-5 రేటింగ్:'))||0);if(score<1||score>5)return;const note=prompt(v9t('Optional feedback:','ఐచ్చిక అభిప్రాయం:'))||'';v9.ratings.unshift({id:v9id(),kind,targetId:id,score,note,by:v9.user?.name||'User',date:new Date().toISOString()});v9save();renderV9Comms();v9toast(v9t('Feedback saved.','అభిప్రాయం సేవ్ అయింది.'));}
function reportV9(id){const reason=prompt(v9t('Reason for report:','ఫిర్యాదు కారణం:'))||'';if(!reason)return;v9.reports.unshift({id:v9id(),targetId:id,reason,by:v9.user?.name||'User',date:new Date().toISOString(),status:'open'});v9save();v9notify(v9t('Report submitted','ఫిర్యాదు పంపబడింది'),reason);renderV9Admin();}
function cloudBackupV9(){const payload={version:'V9',savedAt:new Date().toISOString(),farmerData:typeof data!=='undefined'?data:null,v9};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='RythuMitra_V9_CloudBackup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);v9.cloudBackup={savedAt:payload.savedAt};v9save();document.getElementById('cloudStatus').textContent=v9t('Backup file created. Upload it to your future cloud backend to sync across phones.','బ్యాకప్ ఫైల్ సిద్ధమైంది. ఫోన్ల మధ్య sync కోసం భవిష్యత్ cloud backendలో upload చేయాలి.');}
function importCloudV9(ev){const file=ev.target.files?.[0];if(!file)return;const r=new FileReader();r.onload=()=>{try{const p=JSON.parse(r.result);if(p.farmerData&&typeof data!=='undefined'){data=p.farmerData;localStorage.setItem(KEY,JSON.stringify(data));}if(p.v9){v9=p.v9;v9save();}document.getElementById('cloudStatus').textContent=v9t('Backup restored on this phone.','బ్యాకప్ ఈ ఫోన్‌లో రీస్టోర్ అయింది.');updateUI?.();renderV9All();}catch(e){v9toast(v9t('Invalid backup file.','చెల్లని బ్యాకప్ ఫైల్.'));}};r.readAsText(file);}
function renderV9Dashboard(){const name=v9.user?.name||'Farmer';const crops=(typeof data!=='undefined'&&data.crops)||[];const month=new Date().toISOString().slice(0,7);const income=(typeof data!=='undefined'?(data.sales||[]).filter(x=>String(x.date||'').startsWith(month)).reduce((s,x)=>s+(+x.revenue||(+x.kg||0)*(+x.price||0)),0):0);const expenses=(typeof data!=='undefined'?(data.expenses||[]).filter(x=>String(x.date||'').startsWith(month)).reduce((s,x)=>s+(+x.amount||0),0):0);const el=document.getElementById('v9DashWelcome');if(el)el.textContent=v9t(`Welcome, ${name} 👨‍🌾`,`స్వాగతం, ${name} 👨‍🌾`);const set=(id,val)=>{const x=document.getElementById(id);if(x)x.textContent=val};set('v9DashCrops',crops.length);set('v9DashIncome',money(income));set('v9DashExpenses',money(expenses));set('v9DashProfit',money(income-expenses));set('v9DashListings',(data?.listings||[]).filter(x=>!x.sold).length);}
function renderV9Account(){const auth=document.getElementById('v9AuthBox'),profile=document.getElementById('v9ProfileBox');if(!auth)return;if(v9.session&&v9.user){auth.innerHTML=`<div class="account-banner"><strong>👤 ${v9esc(v9.user.name)}</strong><span>${v9esc(v9.user.mobile)} · ${v9.role}</span><button class="secondary" onclick="logoutV9()">${v9t('Logout','లాగౌట్')}</button></div>`;profile.style.display='block';document.getElementById('profileName').value=v9.user.name||'';document.getElementById('profileState').value=v9.user.state||'Andhra Pradesh';document.getElementById('profileDistrict').value=v9.user.district||'';document.getElementById('profileMandal').value=v9.user.mandal||'';document.getElementById('profileVillage').value=v9.user.village||'';document.getElementById('profileCrops').value=v9.user.farming?.crops||'';document.getElementById('profileLand').value=v9.user.farming?.landArea||'';document.getElementById('profileIrrigation').value=v9.user.farming?.irrigation||'Rainfed';document.getElementById('profileFarming').value=v9.user.farming?.farmingType||'Crop farming';}else{profile.style.display='none';auth.innerHTML=`<div class="auth-tabs"><button onclick="document.getElementById('authMode').value='login';renderV9Account()">${v9t('Login','లాగిన్')}</button><button onclick="document.getElementById('authMode').value='signup';renderV9Account()">${v9t('Sign up','సైన్ అప్')}</button></div><input type="hidden" id="authMode" value="${document.getElementById('authMode')?.value||'login'}"><label>${v9t('Mobile number','మొబైల్ నంబర్')}<input id="authMobile" inputmode="numeric" maxlength="10" placeholder="10-digit mobile"></label>${(document.getElementById('authMode')?.value||'login')==='signup'?`<label>${v9t('Farmer name','రైతు పేరు')}<input id="authName"></label><div class="two-col"><label>State<select id="authState"><option>Andhra Pradesh</option><option>Telangana</option><option>Karnataka</option><option>Tamil Nadu</option><option>Other</option></select></label><label>District<input id="authDistrict"></label></div><div class="two-col"><label>Mandal<input id="authMandal"></label><label>Village<input id="authVillage"></label></div>`:''}<div class="otp-row"><input id="authOtp" inputmode="numeric" maxlength="6" placeholder="OTP"><button class="secondary" onclick="sendDemoOtp()">${v9t('Send OTP','OTP పంపండి')}</button></div><p id="otpHint" class="muted small"></p><button class="primary" onclick="${(document.getElementById('authMode')?.value||'login')==='signup'?'saveFarmerAccount()':'loginFarmer()'}">${(document.getElementById('authMode')?.value||'login')==='signup'?v9t('Create Farmer Account','రైతు ఖాతా సృష్టించండి'):v9t('Login','లాగిన్')}</button><button class="link-btn" onclick="recoverAccount()">${v9t('Account recovery','ఖాతా రికవరీ')}</button>`;}}
function renderV9Buyer(){const el=document.getElementById('buyerArea');if(!el)return;el.innerHTML=`<div class="card"><h3>👤 ${v9t('Buyer Account','కొనుగోలుదారు ఖాతా')}</h3><label>${v9t('Name','పేరు')}<input id="buyerName"></label><label>${v9t('Business name','వ్యాపారం పేరు')}<input id="buyerBusiness"></label><label>${v9t('Location','స్థానం')}<input id="buyerLocation"></label><label>${v9t('Contact mobile','సంప్రదింపు మొబైల్')}<input id="buyerMobile" inputmode="numeric" maxlength="10"></label><label>${v9t('Buyer type','కొనుగోలుదారు రకం')}<select id="buyerType"><option>Individual</option><option>Shop</option><option>Trader</option><option>Business</option></select></label><button class="primary" onclick="buyerRegister()">${v9t('Register / Login Buyer','కొనుగోలుదారు రిజిస్టర్ / లాగిన్')}</button></div><div class="card"><h3>🔎 ${v9t('Buyer marketplace','కొనుగోలుదారు మార్కెట్')}</h3><div class="market-tools"><input id="v9BuyerSearch" placeholder="Search crops / location"><button onclick="renderV9BuyerListings()">${v9t('Search','వెతుకు')}</button></div><div id="v9BuyerListings"></div></div>`;renderV9BuyerListings();}
function renderV9BuyerListings(){const el=document.getElementById('v9BuyerListings');if(!el)return;const q=(document.getElementById('v9BuyerSearch')?.value||'').toLowerCase();const arr=(data?.listings||[]).filter(x=>!x.sold&&(!q||JSON.stringify(x).toLowerCase().includes(q)));el.innerHTML=arr.length?arr.map(x=>`<div class="listing-v9"><div><strong>🌾 ${v9esc(x.cropName||x.crop||'Crop')}</strong><p>${(+x.kg||0).toLocaleString('en-IN')} kg · ${money(x.price)}/kg<br><small>${v9esc(x.location||x.farmer||'Farmer')}</small></p></div><button onclick="sendEnquiryV9(${x.id})">${v9t('Send enquiry','విచారణ పంపండి')}</button></div>`).join(''):`<p class="muted">${v9t('No active listings found.','యాక్టివ్ లిస్టింగ్స్ లేవు.')}</p>`;}
function renderV9Comms(){const el=document.getElementById('v9Comms');if(!el)return;el.innerHTML=(v9.enquiries||[]).map(e=>`<div class="enquiry-v9"><div><strong>🌾 ${v9esc(e.crop)}</strong><p>${v9esc(e.buyer)} · ${v9esc(e.message||'No message')}<br><small>${new Date(e.date).toLocaleString('en-IN')} · ${v9esc(e.status)}</small></p></div><div class="row-actions"><button onclick="updateEnquiryStatus(${e.id},'accepted')">✓</button><button onclick="updateEnquiryStatus(${e.id},'rejected')">✕</button><button onclick="sendMessageV9(${e.id})">💬</button><button onclick="rateV9('buyer','${v9esc(e.buyer)}')">⭐</button><button onclick="reportV9(${e.id})">⚠️</button></div></div>`).join('')||`<p class="muted">${v9t('No enquiries yet.','ఇంకా విచారణలు లేవు.')}</p>`;const msgs=document.getElementById('v9Messages');if(msgs)msgs.innerHTML=(v9.messages||[]).slice(0,30).map(m=>`<div class="message-v9"><strong>${v9esc(m.from)}</strong><p>${v9esc(m.message)}</p><small>${new Date(m.date).toLocaleString('en-IN')}</small></div>`).join('')||'<p class="muted">No messages yet.</p>';}
function renderV9Notifications(){const el=document.getElementById('v9Notifications');if(!el)return;el.innerHTML=(v9.notifications||[]).slice(0,40).map(n=>`<div class="notification-v9 ${n.read?'read':''}"><div><strong>${v9esc(n.title)}</strong><p>${v9esc(n.text)}</p><small>${v9esc(n.date)}</small></div><button onclick="this.parentElement.classList.add('read');v9.notifications.find(x=>x.id===${n.id}).read=true;v9save()">✓</button></div>`).join('')||`<p class="muted">${v9t('No notifications.','నోటిఫికేషన్లు లేవు.')}</p>`;}
function renderV9Admin(){const el=document.getElementById('v9Admin');if(!el)return;el.innerHTML=`<div class="admin-grid"><div class="card"><strong>👨‍🌾 ${v9.buyers.length+1}</strong><span>Accounts / buyers</span></div><div class="card"><strong>${(data?.listings||[]).length}</strong><span>Listings</span></div><div class="card"><strong>${v9.reports.length}</strong><span>Reports</span></div></div><div class="card"><h3>📋 ${v9t('Reports & moderation','ఫిర్యాదులు & మోడరేషన్')}</h3>${v9.reports.map(r=>`<div class="admin-row"><div><strong>#${r.targetId}</strong><p>${v9esc(r.reason)} · ${v9esc(r.by)}</p></div><button onclick="v9.reports.find(x=>x.id===${r.id}).status='resolved';v9save();renderV9Admin()">Resolve</button></div>`).join('')||'<p class="muted">No open reports.</p>'}</div><div class="card"><h3>📢 ${v9t('Announcements','ప్రకటనలు')}</h3><input id="adminAnnouncement" placeholder="Announcement"><button class="primary" onclick="adminPublish()">Publish</button>${v9.announcements.map(a=>`<p>📢 ${v9esc(a.text)} <small>${v9esc(a.date)}</small></p>`).join('')}</div><div class="card"><h3>🏛️ ${v9t('Government schemes','ప్రభుత్వ పథకాలు')}</h3><p class="muted">${v9t('V7 scheme catalogue remains available. Admin controls here are local demo controls; connect to a secure backend for production.','V7 పథకాల కేటలాగ్ కొనసాగుతుంది. ఇవి స్థానిక డెమో నియంత్రణలు; production కోసం సురక్షిత backend అవసరం.')}</p></div>`;}
function adminPublish(){const text=document.getElementById('adminAnnouncement').value.trim();if(!text)return;v9.announcements.unshift({id:v9id(),text,date:new Date().toLocaleString('en-IN')});v9save();v9notify(v9t('New announcement','కొత్త ప్రకటన'),text);renderV9Admin();}
function renderV9All(){renderV9Dashboard();renderV9Account();renderV9Buyer();renderV9Comms();renderV9Notifications();renderV9Admin();}
const _v9Show=showScreen;showScreen=function(id){_v9Show(id);if(id==='account'||id==='v9account')renderV9Account();if(id==='buyer')renderV9Buyer();if(id==='v9comms')renderV9Comms();if(id==='v9notifications')renderV9Notifications();if(id==='v9admin')renderV9Admin();renderV9Dashboard();};
window.addEventListener('load',()=>{renderV9All();});
